"use client";
import {useRef,useState} from "react";import {LabPage,NumberField,Paused,useCopy,labStyles as s} from "@/components/lab-primitives";import {quoteExample,calculateQuote,type QuoteItem} from "@/experiments/quote/model";import {estimate} from "@/experiments/numbers";import styles from "./quote.module.css";
export function QuoteLab(){
 const {t,language,number}=useCopy();const [items,setItems]=useState(quoteExample),[business,setBusiness]=useState(''),[client,setClient]=useState(''),[reference,setReference]=useState('Q-001'),[terms,setTerms]=useState(''),[currency,setCurrency]=useState('DOP');
 const [markup,setMarkup]=useState('0'),[discount,setDiscount]=useState('0'),[tax,setTax]=useState('0');const nextId=useRef(2),[announcement,setAnnouncement]=useState('');
 const r=estimate(()=>calculateQuote(items,markup,discount,tax));const ready=!!r&&!!business.trim()&&!!client.trim()&&items.every(i=>i.name.trim());
 const money=(cents:number)=>new Intl.NumberFormat(language==='es'?'es-DO':'en-US',{style:'currency',currency}).format(cents/100);
 function update(id:string,key:keyof QuoteItem,value:string){setItems(items.map(item=>item.id===id?{...item,[key]:value}:item));}
 return <LabPage code="EXP.008 / QUOTE" title={t('Good work. On paper.','Buen trabajo. Por escrito.')} intro={t('Turn your services into a clear, itemized estimate. Preview the document as you build it.','Convierte tus servicios en una cotización clara y detallada. Mira el documento mientras lo construyes.')} className={styles.page}>
  <div className={styles.desk}><section className={`${s.panel} ${styles.editor}`}><h2>{t('Build your proposal','Arma tu propuesta')}</h2><div className={s.fields}><label className={s.field}>{t('Your business / name','Tu empresa / nombre')}<input id="business" value={business} maxLength={160} onChange={e=>setBusiness(e.target.value)}/></label><label className={s.field}>{t('Client','Cliente')}<input id="client" value={client} maxLength={160} onChange={e=>setClient(e.target.value)}/></label><label className={s.field}>{t('Reference','Referencia')}<input value={reference} maxLength={60} onChange={e=>setReference(e.target.value)}/></label><label className={s.field}>{t('Currency (no conversion)','Moneda (sin conversión)')}<select value={currency} onChange={e=>setCurrency(e.target.value)}>{['DOP','USD','EUR'].map(c=><option key={c}>{c}</option>)}</select></label></div>
   <h3>{t('Services and products','Servicios y productos')}</h3><div className={styles.items}>{items.map((item,index)=><fieldset key={item.id}><legend>{t('Item','Partida')} {index+1}</legend><label className={`${s.field} ${styles.description}`}>{t('Description','Descripción')}<input value={item.name} maxLength={250} onChange={e=>update(item.id,'name',e.target.value)} placeholder={t('Describe the work','Describe el trabajo')}/></label><NumberField id={`qty-${item.id}`} label={t('Quantity','Cantidad')} value={item.quantity} min={.001} max={10000} onChange={v=>update(item.id,'quantity',v)}/><NumberField id={`price-${item.id}`} label={t('Unit price','Precio unitario')} unit={currency} value={item.price} max={1000000} onChange={v=>update(item.id,'price',v)}/><button className={styles.remove} aria-label={t(`Remove item ${index+1}`,`Quitar partida ${index+1}`)} onClick={()=>{setItems(items.filter(i=>i.id!==item.id));setAnnouncement(t('Item removed','Partida eliminada'));}}>×</button></fieldset>)}</div><div className={s.actions}><button disabled={items.length>=100} onClick={()=>{setItems([...items,{id:String(nextId.current++),name:'',quantity:'1',price:'0'}]);setAnnouncement(t('Item added','Partida añadida'));}}>{t('+ Add item','+ Añadir partida')}</button></div>
   <div className={s.fields}><NumberField id="markup" label={t('Markup on subtotal','Recargo sobre subtotal')} unit="%" value={markup} max={1000} onChange={setMarkup}/><NumberField id="discount" label={t('Discount after markup','Descuento tras recargo')} unit="%" value={discount} max={100} onChange={setDiscount}/><NumberField id="tax" label={t('Tax on discounted amount','Impuesto sobre monto descontado')} unit="%" value={tax} max={100} onChange={setTax}/></div><p className={s.note}>{t('Set the applicable tax yourself. No jurisdiction or tax treatment is inferred. Markup is an addition to price, not a profit-margin percentage.','Define tú el impuesto aplicable. No se asume jurisdicción ni tratamiento fiscal. El recargo aumenta el precio; no es un porcentaje de margen de ganancia.')}</p>
   <label className={s.field}>{t('Scope, validity and payment terms','Alcance, vigencia y condiciones de pago')}<textarea value={terms} maxLength={4000} onChange={e=>setTerms(e.target.value)}/></label>
   <div className={s.actions}><button className={s.primary} disabled={!ready} onClick={()=>window.print()}>{t('Print / Save as PDF','Imprimir / Guardar como PDF')}</button></div>
   {!ready&&<p className={s.note}>{t('Add your name, a client and descriptions for all items, and correct numeric values to enable printing.','Añade tu nombre, un cliente y descripciones en todas las partidas, y corrige los números para habilitar la impresión.')}</p>}
   <p className={s.note}>{t('Your draft stays in this tab only. Reloading clears it. Nothing is sent to a server or client.','El borrador permanece solo en esta pestaña. Recargar lo borra. No se envía nada a un servidor ni al cliente.')}</p><p role="status" aria-live="polite">{announcement}</p>
  </section>
  <section className={styles.paper} aria-label={t('Quote preview','Vista previa de cotización')}><header><span>{t('ESTIMATE','COTIZACIÓN')}</span><strong>{reference}</strong></header><h2>{business||t('Your business','Tu empresa')}</h2><p>{t('Prepared for','Preparado para')}<br/><strong>{client||t('Client name','Nombre del cliente')}</strong></p>{!r?<Paused/>:<><div className={s.tableWrap}><table><thead><tr><th>{t('Description','Descripción')}</th><th>{t('Qty','Cant.')}</th><th>{t('Rate','Precio')}</th><th>{t('Amount','Importe')}</th></tr></thead><tbody>{r.rows.map((row,index)=><tr key={row.id}><td>{row.name||`${t('Item','Partida')} ${index+1}`}</td><td>{number(row.quantity,3)}</td><td>{money(Math.round(row.price*100))}</td><td>{money(row.cents)}</td></tr>)}</tbody></table></div><dl>{[[t('Subtotal','Subtotal'),r.subtotal],[t('Markup','Recargo'),r.markupCents],[t('Discount','Descuento'),-r.discountCents],[t('Tax','Impuesto'),r.taxCents]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(Number(value))}</dd></div>)}<div className={styles.total}><dt>{t('TOTAL','TOTAL')}</dt><dd data-testid="quote-total">{money(r.total)}</dd></div></dl></>}<div className={styles.terms}><h3>{t('Scope and terms','Alcance y condiciones')}</h3><p>{terms||t('Add the scope, validity and payment terms before sharing.','Añade el alcance, la vigencia y las condiciones antes de compartir.')}</p></div><footer>{t('Estimate only · Not a tax invoice','Solo cotización · No es comprobante fiscal')} · {currency}</footer></section></div>
 </LabPage>;
}
