"use client";
import {useState} from "react";
import {LabPage,NumberField,Paused,useCopy,labStyles as s} from "@/components/lab-primitives";
import {paintExample,calculatePaint} from "@/experiments/paint/model";
import {estimate} from "@/experiments/numbers";
import {PdfExport} from "@/components/pdf-export";
import styles from "./paint.module.css";
const colors=[['#f77665','Coral','Coral'],['#8aa7c5','Blue','Azul'],['#a8bc97','Sage','Salvia'],['#eab483','Sand','Arena']];
export function PaintLab(){
 const {t,number}=useCopy();const [input,setInput]=useState(paintExample),[ceiling,setCeiling]=useState(false),[color,setColor]=useState(colors[0][0]);
 const r=estimate(()=>calculatePaint(input,ceiling));
 const field=(key:keyof typeof input,label:string,unit:string,min:number,max:number,step:number|'any'='any')=><NumberField id={key} label={label} unit={unit} min={min} max={max} step={step} value={input[key]} onChange={value=>setInput({...input,[key]:value})}/>;
 return <LabPage code="EXP.005 / PAINT" title={t('A fresh coat. A clear plan.','Una nueva mano. Un plan claro.')} intro={t('Start with your room, choose a mood, and work out the paint before opening a can.','Empieza con tu habitación, elige un tono y calcula la pintura antes de abrir un envase.')} className={styles.page}>
  <section className={styles.studio}><div className={styles.room} style={{background:color}} aria-label={t('Illustrative wall color preview','Vista ilustrativa del color de pared')}><div className={styles.window}><i/><i/></div><div className={styles.baseboard}/><span>{t('COLOR STUDY · NOT A PRODUCT MATCH','ESTUDIO DE COLOR · NO ES UN COLOR COMERCIAL')}</span></div><div className={styles.palette}><h2>{t('See the room differently.','Mira tu espacio con otros ojos.')}</h2><p>{t('Try a color. Your quantities stay the same.','Prueba un color. Las cantidades no cambian.')}</p><div role="group" aria-label={t('Preview color','Color de muestra')}>{colors.map(([hex,en,es])=><button key={hex} style={{background:hex}} aria-label={t(en,es)} aria-pressed={color===hex} onClick={()=>setColor(hex)}>{color===hex?'✓':''}</button>)}</div></div></section>
  <div className={styles.recipe}><section className={s.panel}><h2>{t('01 / The surfaces','01 / Las superficies')}</h2><div className={s.fields}>{field('length',t('Room length','Largo del cuarto'),'m',.1,1000)}{field('width',t('Room width','Ancho del cuarto'),'m',.1,1000)}{field('height',t('Wall height','Alto de pared'),'m',.1,100)}{field('openings',t('Doors and windows','Puertas y ventanas'),'m²',0,100000)}</div><label className={styles.check}><input type="checkbox" checked={ceiling} onChange={e=>setCeiling(e.target.checked)}/>{t('Include the ceiling (same paint)','Incluir el techo (misma pintura)')}</label>{Number(input.openings)>=2*(Number(input.length)+Number(input.width))*Number(input.height)&&<p role="alert">{t('Openings must be smaller than the total wall area.','Las aberturas deben ser menores que el área total de paredes.')}</p>}</section>
   <section className={s.panel}><h2>{t('02 / The paint','02 / La pintura')}</h2><div className={s.fields}>{field('coats',t('Coats','Manos'),t('coats','manos'),1,10,1)}{field('coverage',t('Coverage per coat','Rendimiento por mano'),'m²/L',.1,100)}{field('waste',t('Extra allowance','Margen adicional'),'%',0,100)}{field('container',t('Container size','Tamaño del envase'),'L',.1,100)}</div><p className={s.note}>{t('Use the coverage printed on your paint. Absorbent walls, texture and color changes may require more.','Usa el rendimiento indicado en tu pintura. La absorción, textura y los cambios de color pueden requerir más.')}</p></section>
  </div>
  <section className={styles.shopping}><div><h2>{t('03 / Ready for the paint shop','03 / Listo para la tienda')}</h2>{!r?<Paused/>:<><div className={s.stats}><div><span>{t('Paintable area','Área a pintar')}</span><strong>{number(r.area)} m²</strong></div><div><span>{t('Paint with allowance','Pintura con margen')}</span><strong data-testid="liters">{number(r.liters)} L</strong></div><div><span>{t('Containers to buy','Envases a comprar')}</span><strong>{r.cans} × {number(Number(input.container))} L</strong></div></div><div className={s.actions}><PdfExport filename="paint-calculator-estimate" code="EXP.005 / PAINT" title={t("Paint coverage estimate","Estimación de pintura")} summary={t("Paint coverage and container estimate for a rectangular room.","Cobertura de pintura y envases para un cuarto rectangular.")} results={[[t("Paintable area","Área a pintar"),`${number(r.area)} m²`],[t("Paint with allowance","Pintura con margen"),`${number(r.liters)} L`],[t("Containers","Envases"),`${r.cans} × ${number(Number(input.container))} L`]]} notes={[t("Use the paint manufacturer coverage; texture and absorption can change actual use.","Usa el rendimiento del fabricante; la textura y absorción pueden cambiar el consumo real.")]} /></div></>}</div><div className={styles.can} aria-hidden="true"><span>LEILANY<br/>COLOR</span></div></section>
  <div className={s.actions}><button onClick={()=>{setInput(paintExample);setCeiling(false);}}>{t('Reset example','Restablecer ejemplo')}</button></div>
  <details><summary>{t('Coverage math','Cálculo de cobertura')}</summary><p>{t('Walls = 2 × (length + width) × height − openings. Add length × width when including the ceiling. Liters = area × coats ÷ coverage × (1 + allowance / 100). Containers are rounded up.','Paredes = 2 × (largo + ancho) × alto − aberturas. Suma largo × ancho si incluyes el techo. Litros = área × manos ÷ rendimiento × (1 + margen / 100). Los envases se redondean hacia arriba.')}</p><p className={s.note}>{t('Rectangular room, one paint product. Primer, trim and repairs are not included. Separate products or colors need separate estimates.','Habitación rectangular, un solo producto. No incluye imprimación, molduras ni reparaciones. Calcula por separado los productos o colores diferentes.')}</p></details>
 </LabPage>;
}
