"use client";
import {PdfExport} from "@/components/pdf-export";
import {useRef,useState} from "react";import {LabPage,NumberField,Paused,useCopy,labStyles as s} from "@/components/lab-primitives";import {furnitureExample,furnitureOptions,calculateFurniture,type FurnitureItem,type MaterialKind} from "@/experiments/furniture/model";import {estimate} from "@/experiments/numbers";import styles from "./furniture.module.css";
export function FurnitureLab(){
 const {t,language}=useCopy();const [items,setItems]=useState(furnitureExample),[input,setInput]=useState(furnitureOptions),[currency,setCurrency]=useState('DOP');const nextId=useRef(5);const r=estimate(()=>calculateFurniture(items,input));
 const money=(n:number)=>new Intl.NumberFormat(language==='es'?'es-DO':'en-US',{style:'currency',currency}).format(n/100);
 const displayName=(name:string)=>({ 'Top panel':t('Top panel','Tablero superior'),Leg:t('Leg','Pata'),'Hardware kit':t('Hardware kit','Juego de herrajes'),Finish:t('Finish','Acabado') }[name]||name);
 const category=(kind:MaterialKind)=>kind==='material'?t('Materials','Materiales'):kind==='hardware'?t('Hardware','Herrajes'):t('Finish','Acabado');
 function update(id:string,key:keyof FurnitureItem,value:string){setItems(items.map(item=>item.id===id?{...item,[key]:value}:item));}
 const field=(key:keyof typeof input,label:string,unit:string,max:number)=><NumberField id={key} label={label} unit={unit} max={max} value={input[key]} onChange={v=>setInput({...input,[key]:v})}/>;
 return <LabPage code="EXP.009 / FURNITURE" title={t('Good ideas, built to budget.','Buenas ideas, dentro del presupuesto.')} intro={t('Build the bill of materials, add the hands-on work, and see the true shape of your project cost.','Arma la lista de materiales, añade el trabajo del taller y conoce el costo de tu proyecto.')} className={styles.page}>
  <div className={styles.workshop}><section className={styles.parts}><div className={styles.partHeader}><h2>{t('01 / Parts on the workbench','01 / Piezas sobre la mesa')}</h2><label className={s.field}>{t('Currency','Moneda')}<select value={currency} onChange={e=>setCurrency(e.target.value)}>{['DOP','USD','EUR'].map(c=><option key={c}>{c}</option>)}</select></label></div>
   {items.map((item,index)=><fieldset className={styles.part} key={item.id}><legend>{t('Part','Pieza')} {index+1}</legend><label className={s.field}>{t('Description','Descripción')}<input value={displayName(item.name)} maxLength={180} onChange={e=>update(item.id,'name',e.target.value)}/></label><label className={s.field}>{t('Category','Categoría')}<select value={item.kind} onChange={e=>update(item.id,'kind',e.target.value)}>{(['material','hardware','finish'] as const).map(kind=><option key={kind} value={kind}>{category(kind)}</option>)}</select></label><NumberField id={`qty-${item.id}`} label={t('Quantity','Cantidad')} value={item.quantity} min={.001} max={10000} onChange={v=>update(item.id,'quantity',v)}/><NumberField id={`price-${item.id}`} label={t('Unit cost','Costo unitario')} unit={currency} value={item.price} max={1000000} onChange={v=>update(item.id,'price',v)}/><button aria-label={t(`Remove part ${index+1}`,`Quitar pieza ${index+1}`)} onClick={()=>setItems(items.filter(i=>i.id!==item.id))}>×</button></fieldset>)}
   <div className={s.actions}><button disabled={items.length>=100} onClick={()=>setItems([...items,{id:String(nextId.current++),name:'',kind:'material',quantity:'1',price:'0'}])}>{t('+ Add part','+ Añadir pieza')}</button><button onClick={()=>{setItems(furnitureExample);setInput(furnitureOptions);}}>{t('Reset example','Restablecer ejemplo')}</button></div><p className={s.note}>{t('Use matching quantity and price units: sheets, pieces, meters or liters. Prices are your estimates; no live supplier pricing or currency conversion.','Usa unidades compatibles para cantidad y precio: tableros, piezas, metros o litros. Los precios son tus estimaciones; no hay precios en vivo ni conversión de moneda.')}</p>
  </section><aside className={styles.assembly}><span>{t('MATERIAL · CRAFT · CARE','MATERIAL · OFICIO · CUIDADO')}</span><svg viewBox="0 0 400 250" role="img" aria-label={t('Illustrative table assembly, not a cut plan','Ensamble de mesa ilustrativo, no un plano de corte')}><path d="M45 60 290 20 360 70 110 115Z" fill="#f4dfc7"/><path d="M45 60V77L110 132V115M110 132 360 87V70" fill="#8b4b31"/><path d="M75 135V230H92V145M310 120V220H327V120M120 165V247H137V165" fill="#8b4b31"/><path d="M80 105V135M315 90V120M125 140V165" stroke="#8b4b31" strokeWidth="2" strokeDasharray="5 5"/></svg><h2>{t('Every piece has a part to play.','Cada pieza cuenta.')}</h2><p>{t('Illustration only. This tool estimates costs, not structural suitability or optimized cuts.','Solo ilustración. La herramienta estima costos, no resistencia estructural ni cortes optimizados.')}</p></aside></div>
  <section className={s.panel}><h2>{t('02 / Time and workshop costs','02 / Tiempo y costos del taller')}</h2><div className={styles.inputs}>{field('hours',t('Labor hours','Horas de trabajo'),'h',100000)}{field('rate',t('Hourly rate','Tarifa por hora'),currency,1000000)}{field('waste',t('Material waste only','Desperdicio solo de materiales'),'%',100)}{field('overhead',t('Overhead on direct costs','Gastos sobre costos directos'),'%',100)}{field('markup',t('Optional selling markup','Recargo de venta opcional'),'%',1000)}</div></section>
  <section className={styles.budget}><h2>{t('03 / The project, added up','03 / El proyecto, sumado')}</h2>{!r?<Paused/>:<><div className={styles.breakdown}>{[[category('material'),r.groups.material+r.waste],[category('hardware'),r.groups.hardware],[category('finish'),r.groups.finish],[t('Labor','Mano de obra'),r.labor],[t('Overhead','Gastos del taller'),r.overhead]].map(([label,value])=><div key={label}><div><span>{label}</span><strong>{money(Number(value))}</strong></div><div className={styles.track}><i style={{width:`${r.cost?Number(value)/r.cost*100:0}%`}}/></div></div>)}</div><div className={styles.summary}><div><span>{t('Estimated build cost','Costo estimado de fabricación')}</span><strong data-testid="build-cost">{money(r.cost)}</strong></div><div><span>{t('Price with markup, before tax','Precio con recargo, antes de impuestos')}</span><strong>{money(r.price)}</strong></div></div></>}</section>
  <p className={s.note}>{t('Waste applies only to the materials category. Overhead applies to materials, waste, fittings, finish and labor. Selling markup applies to the resulting build cost; it is not a profit-margin percentage. Taxes, delivery and installation are excluded unless you add them as parts. Changing currency does not convert values.','El desperdicio se aplica solo a materiales. Los gastos se aplican a materiales, desperdicio, herrajes, acabado y mano de obra. El recargo de venta se aplica al costo final; no es un porcentaje de margen. No incluye impuestos, transporte ni instalación, salvo que los añadas como partidas. Cambiar la moneda no convierte valores.')}</p>
 <div className="pdf-actions"><PdfExport filename="furniture-budget-estimate" code="EXP.009 / FURNITURE" title={t("Furniture budget","Presupuesto de muebles")} summary={t("Parts, labor and workshop cost estimate.","Estimación de piezas, mano de obra y costos del taller.")} disabled={!r} results={r ? [[t("Materials before waste","Materiales sin desperdicio"),money(r.groups.material)],[t("Waste","Desperdicio"),money(r.waste)],[t("Hardware","Herrajes"),money(r.groups.hardware)],[t("Finish","Acabado"),money(r.groups.finish)],[t("Labor","Mano de obra"),money(r.labor)],[t("Overhead","Gastos del taller"),money(r.overhead)],[t("Build cost","Costo de fabricación"),money(r.cost)],[t("Price before tax","Precio antes de impuestos"),money(r.price)]] : []} /></div>
 </LabPage>;
}
