"use client";
import {useState} from "react";import {LabPage,NumberField,Paused,useCopy,labStyles as s} from "@/components/lab-primitives";
import {climateExample,calculateClimate,type Exposure} from "@/experiments/climate/model";import {estimate} from "@/experiments/numbers";import styles from "./climate.module.css";
export function ClimateLab(){
 const {t,number}=useCopy();const [input,setInput]=useState(climateExample),[exposure,setExposure]=useState<Exposure>('normal'),[kitchen,setKitchen]=useState(false);const r=estimate(()=>calculateClimate(input,exposure,kitchen));
 const field=(key:keyof typeof input,label:string,unit:string,min:number,max:number,step:number|'any'='any')=><NumberField id={key} label={label} unit={unit} min={min} max={max} step={step} value={input[key]} onChange={value=>setInput({...input,[key]:value})}/>;
 const area=Number(input.length)*Number(input.width),outside=Number.isFinite(area)&&(area<9.290304||area>232.2576);
 return <LabPage code="EXP.006 / CLIMATE" title={t('Room for a little comfort.','Espacio para sentirte bien.')} intro={t('Explore a starting cooling capacity for a rectangular room, with the assumptions in plain sight.','Explora una capacidad de enfriamiento inicial para un cuarto rectangular, con los supuestos a la vista.')} className={styles.page}>
  <div className={styles.layout}><section className={styles.atmosphere} aria-labelledby="cooling-title"><span>{t('A COOLER STARTING POINT','UN PUNTO DE PARTIDA MÁS FRESCO')}</span><div className={styles.unit} aria-hidden="true"><span>LEILANY AIR</span><i/><i/></div><svg viewBox="0 0 400 95" aria-hidden="true"><path d="M110 0C150 40 70 55 100 90M200 0C240 40 160 55 190 90M290 0C330 40 250 55 280 90" fill="none" stroke="#7662bd" strokeWidth="3"/></svg><h2 id="cooling-title">{t('Estimated cooling capacity','Capacidad de enfriamiento estimada')}</h2>{r?<><strong className={styles.reading} data-testid="cooling">{number(r.total,0)} <small>BTU/h</small></strong><p>{number(r.area)} m² · {number(r.ft2,0)} ft²</p></>:<Paused/>}<p className={styles.caveat}>{t('Reference ceiling: 2.44 m (8 ft). Room AC guide, not a mini-split or whole-building design.','Techo de referencia: 2.44 m (8 pies). Guía para aire de habitación, no un diseño de minisplit ni de edificio completo.')}</p></section>
  <section className={s.panel}><h2>{t('Tell us about the room','Cuéntanos sobre el cuarto')}</h2><div className={s.fields}>{field('length',t('Length','Largo'),'m',1,100)}{field('width',t('Width','Ancho'),'m',1,100)}{field('people',t('Regular occupants','Ocupantes habituales'),t('people','personas'),0,100,1)}<label className={s.field}>{t('Sun exposure','Exposición solar')}<select value={exposure} onChange={e=>setExposure(e.target.value as Exposure)}><option value="shade">{t('Heavily shaded','Mucha sombra')}</option><option value="normal">{t('Typical exposure','Exposición normal')}</option><option value="sun">{t('Very sunny','Mucho sol')}</option></select></label></div><label className={styles.check}><input type="checkbox" checked={kitchen} onChange={e=>setKitchen(e.target.checked)}/>{t('This room is a kitchen','Este cuarto es una cocina')}</label>{outside&&<p role="alert" className={s.note}>{t('The source chart covers 100–2,500 ft² (approximately 9.29–232.26 m²). No estimate is extrapolated outside that range.','La tabla fuente cubre 100–2,500 pies² (aproximadamente 9.29–232.26 m²). No se extrapola fuera de ese rango.')}</p>}<div className={s.actions}><button onClick={()=>{setInput(climateExample);setExposure('normal');setKitchen(false);}}>{t('Reset example','Restablecer ejemplo')}</button></div>
  {r&&<div className={styles.factors}><h3>{t('Where the number comes from','De dónde sale el número')}</h3>{[[t('Area baseline','Base por área'),r.base],[t('Sun adjustment','Ajuste por sol'),r.solar],[t('Extra occupants','Ocupantes adicionales'),r.occupancy],[t('Kitchen adjustment','Ajuste por cocina'),r.kitchenLoad]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value)>0?'+':''}{number(Number(value),0)} BTU/h</strong></div>)}</div>}</section></div>
  <aside className={s.note}><p>{t('Based on','Basado en')} <a href="https://www.energystar.gov/products/room_air_conditioners" target="_blank" rel="noreferrer">ENERGY STAR — Room Air Conditioners ↗</a> · {t('Reviewed September 29, 2026.','Revisado el 29 de septiembre de 2026.')}</p><p>{t('The chart uses floor-area bands. Shade/sun changes the baseline by −10%/+10%; each person beyond two adds 600 BTU/h; a kitchen adds 4,000 BTU/h. At an exact band boundary this tool uses the lower capacity.','La tabla usa rangos de superficie. Sombra/sol ajusta la base −10%/+10%; cada persona después de dos suma 600 BTU/h; una cocina suma 4,000 BTU/h. En un límite exacto se usa la capacidad inferior.')}</p><p>{t('Local climate, humidity, glazing, insulation and high ceilings need a professional load assessment. Do not select equipment from this number alone.','El clima local, humedad, ventanas, aislamiento y techos altos requieren una evaluación profesional de carga. No selecciones un equipo basándote solo en este número.')}</p></aside>
 </LabPage>;
}
