"use client";
import {useState} from "react";import {LabPage,NumberField,Paused,useCopy,labStyles as s} from "@/components/lab-primitives";import {financeExample,calculateFinance} from "@/experiments/finance/model";import {estimate} from "@/experiments/numbers";import styles from "./finance.module.css";
export function FinanceLab(){
 const {t,number,language}=useCopy();const [input,setInput]=useState(financeExample),[currency,setCurrency]=useState('DOP'),[all,setAll]=useState(false);const r=estimate(()=>calculateFinance(input));
 const money=(n:number)=>new Intl.NumberFormat(language==='es'?'es-DO':'en-US',{style:'currency',currency,maximumFractionDigits:2}).format(n);
 const field=(key:keyof typeof input,label:string,unit:string,min:number,max:number,step:number|'any'='any')=><NumberField id={key} label={label} unit={unit} min={min} max={max} step={step} value={input[key]} onChange={value=>setInput({...input,[key]:value})}/>;
 function download(){if(!r)return;const header=t('Month,Payment,Interest,Principal,Balance','Mes,Cuota,Interes,Capital,Saldo');const text=header+'\r\n'+r.rows.map(row=>[row.month,...[row.payment,row.interest,row.principal,row.balance].map(n=>n.toFixed(2))].join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`amortization-${currency}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <LabPage code="EXP.007 / FINANCE" title={t('Give your numbers a future.','Dale un futuro a tus números.')} intro={t('Follow a fixed-rate loan from the first payment to the last. See what an extra payment can change.','Sigue un préstamo de tasa fija desde la primera cuota hasta la última. Mira qué cambia con un abono adicional.')} className={styles.page}>
  <section className={`${s.panel} ${styles.terms}`}><h2>{t('The starting numbers','Los números iniciales')}</h2><div className={styles.inputs}>{field('principal',t('Loan amount','Monto del préstamo'),currency,1,100000000)}{field('rate',t('Nominal annual interest','Interés nominal anual'),'%',0,100)}{field('months',t('Loan term','Plazo'),t('months','meses'),1,600,1)}{field('extra',t('Extra principal per month','Abono extra mensual'),currency,0,100000000)}<label className={s.field}>{t('Display currency','Moneda de presentación')}<select value={currency} onChange={e=>setCurrency(e.target.value)}>{['DOP','USD','EUR'].map(c=><option key={c}>{c}</option>)}</select></label></div><p className={s.note}>{t('Currency changes labels only; no exchange conversion. Use the contract interest rate, not APR. Fees, insurance, taxes and early-payment penalties are excluded.','La moneda solo cambia las etiquetas; no convierte divisas. Usa la tasa de interés del contrato, no la TAE/APR. No incluye comisiones, seguros, impuestos ni penalidades de prepago.')}</p></section>
  {!r?<Paused/>:<><section className={styles.journey}><div className={styles.payment}><span>{t('BASE MONTHLY PAYMENT','CUOTA MENSUAL BASE')}</span><strong data-testid="payment">{money(r.payment)}</strong><p>{t('Before your optional extra payment','Antes del abono extra opcional')}</p><div><span>{t('Paid off in','Se liquida en')}</span><b>{r.months} {t('months','meses')}</b></div></div><div className={styles.chart}><h2>{t('A balance moving toward zero.','Un saldo que se acerca a cero.')}</h2><svg viewBox="0 0 620 205" role="img" aria-label={t('Remaining balance decreases over the payment schedule','El saldo pendiente disminuye a lo largo del calendario de pagos')}><path d="M10 180H610M10 15V180" stroke="#7662bd" fill="none"/><polyline points={`10,15 ${r.rows.map((row,i)=>`${10+(i+1)/r.rows.length*600},${180-row.balance/r.principal*165}`).join(' ')}`} fill="none" stroke="#543d8e" strokeWidth="4"/><text x="10" y="202">{t('START','INICIO')}</text><text x="610" y="202" textAnchor="end">{t('PAID OFF','LIQUIDADO')}</text></svg><div className={styles.totals}><div><span>{t('Interest','Intereses')}</span><strong>{money(r.totalInterest)}</strong></div><div><span>{t('Total repaid','Total pagado')}</span><strong>{money(r.totalPaid)}</strong></div></div></div></section>
  <section className={s.panel}><h2>{t('Your payment timeline','Tu calendario de pagos')}</h2><div className={s.actions}><button onClick={()=>setAll(!all)}>{all?t('Show first 12 months','Ver primeros 12 meses'):t('Show full schedule','Ver calendario completo')}</button><button onClick={download}>{t('Download CSV','Descargar CSV')}</button></div><div className={s.tableWrap}><table><caption>{t(`Showing ${all?r.rows.length:Math.min(12,r.rows.length)} of ${r.rows.length} payments`, `Mostrando ${all?r.rows.length:Math.min(12,r.rows.length)} de ${r.rows.length} cuotas`)} · {currency}</caption><thead><tr>{[t('Month','Mes'),t('Payment','Cuota'),t('Interest','Interés'),t('Principal','Capital'),t('Balance','Saldo')].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{(all?r.rows:r.rows.slice(0,12)).map(row=><tr key={row.month}><th scope="row">{row.month}</th><td>{number(row.payment)}</td><td>{number(row.interest)}</td><td>{number(row.principal)}</td><td>{number(row.balance)}</td></tr>)}</tbody></table></div></section></>}
  <div className={s.actions}><button onClick={()=>{setInput(financeExample);setAll(false);}}>{t('Reset example','Restablecer ejemplo')}</button></div><details><summary>{t('Method and limitations','Método y limitaciones')}</summary><p>{t('Monthly rate r = nominal annual rate ÷ 1,200. Payment = P × r ÷ (1 − (1+r)⁻ⁿ). At zero interest, payment = P ÷ n. Interest is applied to the outstanding balance before each end-of-month payment. Extra payments reduce the term, not the base payment.','Tasa mensual r = tasa nominal anual ÷ 1,200. Cuota = P × r ÷ (1 − (1+r)⁻ⁿ). Con interés cero, cuota = P ÷ n. El interés se aplica al saldo antes de cada pago a fin de mes. Los abonos extra reducen el plazo, no la cuota base.')}</p><p className={s.note}>{t('An illustrative estimate, not an offer or financial advice. Internal calculations are unrounded; displayed values are rounded to cents, so row sums can differ slightly. Your lender may use daily interest and different rounding.','Estimación ilustrativa, no una oferta ni asesoría financiera. Los cálculos internos no se redondean; la presentación usa centavos, por lo que las sumas pueden variar ligeramente. Tu entidad puede usar interés diario y otro redondeo.')}</p><a href="https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-mortgage-interest-rate-and-an-apr-en-135/" target="_blank" rel="noreferrer">{t('CFPB: interest rate versus APR ↗','CFPB: tasa de interés frente a APR ↗')}</a></details>
 </LabPage>;
}
